asgard: http://maclay.thormobile5.net/TG0000.xml

worthy: thor
unworthy: loki

pin_descriptions:
  - 3.3v
  - 5v
  - GPIO02
  - 5v
  - GPIO03
  - Ground
  - GPIO04
  - GPIO14
  - Ground
  - GPIO15
  - GPIO17
  - GPIO18
  - GPIO27
  - Ground
  - GPIO22
  - GPIO23
  - 3.3v
  - GPIO24
  - GPIO10
  - Ground
  - GPIO09
  - GPIO25
  - GPIO11
  - GPIO08
  - Ground
  - GPIO07
  - ID_SD
  - ID_SC
  - GPIO05
  - Ground
  - GPIO06
  - GPIO12
  - GPIO13
  - Ground
  - GPIO19
  - GPIO16
  - GPIO26
  - GPIO20
  - Ground
  - GPIO21
